USE MuOnline
ALTER TABLE RewardItem ADD iJOHOpt TINYINT NOT NULL DEFAULT 0
ALTER TABLE RewardItem ADD i380Opt TINYINT NOT NULL DEFAULT 0
ALTER TABLE RewardItem ADD iSocket1 TINYINT NOT NULL DEFAULT 255
ALTER TABLE RewardItem ADD iSocket2 TINYINT NOT NULL DEFAULT 255
ALTER TABLE RewardItem ADD iSocket3 TINYINT NOT NULL DEFAULT 255
ALTER TABLE RewardItem ADD iSocket4 TINYINT NOT NULL DEFAULT 255
ALTER TABLE RewardItem ADD iSocket5 TINYINT NOT NULL DEFAULT 255
