USE MUONLINE
ALTER TABLE Character ALTER COLUMN Strength INT
ALTER TABLE Character ALTER COLUMN Dexterity INT
ALTER TABLE Character ALTER COLUMN Vitality INT
ALTER TABLE Character ALTER COLUMN Energy INT
ALTER TABLE Character ALTER COLUMN Leadership INT
