@echo off

del ..\..\Me_MuOnline\CashShopServer\Log\* /q
del ..\..\Me_MuOnline\ChatServer\Log\* /q
del ..\..\Me_MuOnline\ConnectServer\LOG_ERROR\* /q
del ..\..\Me_MuOnline\ConnectServer\LOG_GSINFO\* /q
del ..\..\Me_MuOnline\EventServer\Log\* /q
del ..\..\Me_MuOnline\JoinServer\Log\* /q
del ..\..\Me_MuOnline\Log\* /q
del ..\..\Me_MuOnline\RankingServer\LOG_ERROR\* /q
del ..\..\Me_MuOnline\RankingServer\LOG_POINT\* /q
del ..\..\MuOnline\DataServer1\ITEM_SERIAL_LOG\* /q
del ..\..\MuOnline\DataServer1\Log\* /q
del ..\..\MuOnline\DataServer2\ITEM_SERIAL_LOG\* /q
del ..\..\MuOnline\DataServer2\Log\* /q
del ..\..\MuOnline\eDS\Log\* /q
del ..\..\MuOnline\ExDB\Log\* /q
del ..\..\MuOnline\Log\* /q
del ..\..\MuOnline\GameServer\KANTURU_TEST_LOG\* /q
del ..\..\MuOnline\GameServer\KUNDUN_EVENT_GM_LOG\* /q
del ..\..\MuOnline\GameServer\KUNDUN_EVENT_LOG\* /q
del ..\..\MuOnline\GameServer\GMLog\* /q
del ..\..\MuOnline\GameServer\Log\* /q
del ..\..\MuOnline\GameServer\RAKLION_TEST_LOG\* /q
del ..\..\MuOnline\GameServer\SERVER_CONN_STATE_LOG\* /q
del ..\..\MuOnline\GameServer_CS\KANTURU_TEST_LOG\* /q
del ..\..\MuOnline\GameServer_CS\KUNDUN_EVENT_GM_LOG\* /q
del ..\..\MuOnline\GameServer_CS\KUNDUN_EVENT_LOG\* /q
del ..\..\MuOnline\GameServer_CS\GMLog\* /q
del ..\..\MuOnline\GameServer_CS\Log\* /q
del ..\..\MuOnline\GameServer_CS\RAKLION_TEST_LOG\* /q
del ..\..\MuOnline\GameServer_CS\SERVER_CONN_STATE_LOG\* /q